swiftmailer:
    transport: smtp
    host: 'smtp.gmail.com'
    port: 587
    encryption: tls
    username: 'danieljimplaysix@gmail.com'
    password: 'stfycqrmuaahqcst'
              
    spool: {type: memory}
